name: pagination_dropdown_list
description: "flutter drop down list with paganation that enable you to fectch data while scrolling. "
version: 0.1.7

homepage: https://github.com/Mahfoud-Sa/pagination_dropdown_list

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:


#للتشفير
dartdoc:
exclude:
  - lib/src/**
nodoc:
  - lib/src/**
